export * from './Navbar'
export * from './Footer'
export * from './SideMenu'
export * from './Nosotros'
export * from './Industrias'
export * from './Oil'
export * from './Mantenimiento'
export * from './Comercializacion'